---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: data/intro.json
  label: Intro Section
  match: "**/*"
- type: document
  path: data/about.json
  label: About Section
  match: "**/*"
- type: document
  path: data.projects.json
  label: Projects Section
  match: "**/*"
- type: document
  path: data/contact.json
  label: Contact Section
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
