backend:
  name: github
  repo: travisfrazier/vue-portfolio

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "intro"
    label: "Intro Section"
    folder: "sections"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Body", name: "body", widget: "markdown"}