backend:
  name: github
  repo: travisfrazier/vue-portfolio

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "About "
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Intro, name: intro, widget: text}